{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mycelium-backend.fullname" . }}
  labels:
    {{- include "mycelium-backend.labels" . | nindent 4 }}
spec:
  {{- if or .Values.gateway.gatewayName .Values.gateway.gatewayNamespace }}
  parentRefs:
    - name: {{ .Values.gateway.gatewayName | default "gateway" }}
      {{- if .Values.gateway.gatewayNamespace }}
      namespace: {{ .Values.gateway.gatewayNamespace }}
      {{- end }}
      sectionName: https
  {{- else }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      sectionName: https
  {{- end }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "mycelium-backend.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}