{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mycelium-backend.fullname" . }}-db-secret
  labels:
    {{- include "mycelium-backend.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.config.database.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mycelium-backend.fullname" . }}-s3-secret
  labels:
    {{- include "mycelium-backend.labels" . | nindent 4 }}
type: Opaque
data:
  secretKey: {{ .Values.config.s3.secretKey | b64enc | quote }}
{{- end }}