/* tslint:disable */
/* eslint-disable */
/**
 * Mycelium API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface IntervalA
 */
export interface IntervalA {
    /**
     * 
     * @type {number}
     * @memberof IntervalA
     */
    'start': number;
    /**
     * 
     * @type {number}
     * @memberof IntervalA
     */
    'end': number;
}
/**
 * 
 * @export
 * @interface PlantProfile
 */
export interface PlantProfile {
    /**
     * 
     * @type {string}
     * @memberof PlantProfile
     */
    'name': string;
    /**
     * 
     * @type {PlantProfileVariables}
     * @memberof PlantProfile
     */
    'variables': PlantProfileVariables;
}
/**
 * 
 * @export
 * @interface PlantProfileVariables
 */
export interface PlantProfileVariables {
    /**
     * 
     * @type {IntervalA}
     * @memberof PlantProfileVariables
     */
    'lightMmol': IntervalA;
    /**
     * 
     * @type {IntervalA}
     * @memberof PlantProfileVariables
     */
    'lightLux': IntervalA;
    /**
     * 
     * @type {IntervalA}
     * @memberof PlantProfileVariables
     */
    'temperature': IntervalA;
    /**
     * 
     * @type {IntervalA}
     * @memberof PlantProfileVariables
     */
    'humidity': IntervalA;
    /**
     * 
     * @type {IntervalA}
     * @memberof PlantProfileVariables
     */
    'soilMoisture': IntervalA;
    /**
     * 
     * @type {IntervalA}
     * @memberof PlantProfileVariables
     */
    'soilEc': IntervalA;
}
/**
 * 
 * @export
 * @interface Station
 */
export interface Station {
    /**
     * 
     * @type {string}
     * @memberof Station
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Station
     */
    'mac': string;
    /**
     * 
     * @type {string}
     * @memberof Station
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Station
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof Station
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Station
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof Station
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof Station
     */
    'updated'?: string;
}
/**
 * 
 * @export
 * @interface StationDetails
 */
export interface StationDetails {
    /**
     * 
     * @type {Station}
     * @memberof StationDetails
     */
    'station': Station;
    /**
     * 
     * @type {Array<StationMeasurement>}
     * @memberof StationDetails
     */
    'measurements'?: Array<StationMeasurement>;
}
/**
 * 
 * @export
 * @interface StationInsert
 */
export interface StationInsert {
    /**
     * 
     * @type {string}
     * @memberof StationInsert
     */
    'mac': string;
    /**
     * 
     * @type {string}
     * @memberof StationInsert
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface StationLog
 */
export interface StationLog {
    /**
     * 
     * @type {string}
     * @memberof StationLog
     */
    'stationId': string;
    /**
     * 
     * @type {string}
     * @memberof StationLog
     */
    'on': string;
    /**
     * 
     * @type {Watered}
     * @memberof StationLog
     */
    'event': Watered;
}
/**
 * 
 * @export
 * @interface StationMeasurement
 */
export interface StationMeasurement {
    /**
     * 
     * @type {string}
     * @memberof StationMeasurement
     */
    'on': string;
    /**
     * 
     * @type {number}
     * @memberof StationMeasurement
     */
    'batteryVoltage': number;
    /**
     * 
     * @type {number}
     * @memberof StationMeasurement
     */
    'temperature': number;
    /**
     * 
     * @type {number}
     * @memberof StationMeasurement
     */
    'humidity': number;
    /**
     * 
     * @type {number}
     * @memberof StationMeasurement
     */
    'lux': number;
    /**
     * 
     * @type {number}
     * @memberof StationMeasurement
     */
    'soilPf': number;
    /**
     * 
     * @type {number}
     * @memberof StationMeasurement
     */
    'tankPf': number;
}
/**
 * 
 * @export
 * @interface StationPlantProfile
 */
export interface StationPlantProfile {
    /**
     * 
     * @type {string}
     * @memberof StationPlantProfile
     */
    'stationId': string;
    /**
     * 
     * @type {string}
     * @memberof StationPlantProfile
     */
    'mac': string;
    /**
     * 
     * @type {PlantProfile}
     * @memberof StationPlantProfile
     */
    'profile': PlantProfile;
}
/**
 * 
 * @export
 * @interface StationUpdate
 */
export interface StationUpdate {
    /**
     * 
     * @type {string}
     * @memberof StationUpdate
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof StationUpdate
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof StationUpdate
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface Watered
 */
export interface Watered {
    /**
     * 
     * @type {string}
     * @memberof Watered
     */
    'period': string;
    /**
     * 
     * @type {string}
     * @memberof Watered
     */
    '_type': WateredTypeEnum;
}

export const WateredTypeEnum = {
    Watered: 'Watered'
} as const;

export type WateredTypeEnum = typeof WateredTypeEnum[keyof typeof WateredTypeEnum];

/**
 * 
 * @export
 * @interface Watering
 */
export interface Watering {
    /**
     * 
     * @type {string}
     * @memberof Watering
     */
    'watering'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {StationInsert} stationInsert 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addStation: async (stationInsert: StationInsert, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationInsert' is not null or undefined
            assertParamExists('addStation', 'stationInsert', stationInsert)
            const localVarPath = `/stations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(stationInsert, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} stationId 
         * @param {Array<StationMeasurement>} [stationMeasurement] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkinStation: async (stationId: string, stationMeasurement?: Array<StationMeasurement>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('checkinStation', 'stationId', stationId)
            const localVarPath = `/stations/{stationId}/checkin`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(stationMeasurement, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStation: async (stationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('deleteStation', 'stationId', stationId)
            const localVarPath = `/stations/{stationId}`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProfiles: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/profiles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} stationId 
         * @param {string} [period] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStation: async (stationId: string, period?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('getStation', 'stationId', stationId)
            const localVarPath = `/stations/{stationId}`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} stationId 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStationLog: async (stationId: string, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('getStationLog', 'stationId', stationId)
            const localVarPath = `/stations/{stationId}/log`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStationProfile: async (stationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('getStationProfile', 'stationId', stationId)
            const localVarPath = `/stations/{stationId}/profile`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listStations: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} stationId 
         * @param {PlantProfile} plantProfile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setProfile: async (stationId: string, plantProfile: PlantProfile, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('setProfile', 'stationId', stationId)
            // verify required parameter 'plantProfile' is not null or undefined
            assertParamExists('setProfile', 'plantProfile', plantProfile)
            const localVarPath = `/profiles/profile/{stationId}`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(plantProfile, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} stationId 
         * @param {StationUpdate} stationUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStation: async (stationId: string, stationUpdate: StationUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('updateStation', 'stationId', stationId)
            // verify required parameter 'stationUpdate' is not null or undefined
            assertParamExists('updateStation', 'stationUpdate', stationUpdate)
            const localVarPath = `/stations/{stationId}`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(stationUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} stationId 
         * @param {File} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadAvatar: async (stationId: string, body: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('uploadAvatar', 'stationId', stationId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('uploadAvatar', 'body', body)
            const localVarPath = `/stations/{stationId}/upload`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/octet-stream';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        viewAvatar: async (stationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('viewAvatar', 'stationId', stationId)
            const localVarPath = `/stations/{stationId}/avatar`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} stationId 
         * @param {Watering} watering 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wateredAtStation: async (stationId: string, watering: Watering, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('wateredAtStation', 'stationId', stationId)
            // verify required parameter 'watering' is not null or undefined
            assertParamExists('wateredAtStation', 'watering', watering)
            const localVarPath = `/stations/{stationId}/watered`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication httpAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(watering, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {StationInsert} stationInsert 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addStation(stationInsert: StationInsert, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addStation(stationInsert, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.addStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} stationId 
         * @param {Array<StationMeasurement>} [stationMeasurement] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkinStation(stationId: string, stationMeasurement?: Array<StationMeasurement>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Watering>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkinStation(stationId, stationMeasurement, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.checkinStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteStation(stationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteStation(stationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProfiles(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<StationPlantProfile>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProfiles(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getProfiles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} stationId 
         * @param {string} [period] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStation(stationId: string, period?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StationDetails>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStation(stationId, period, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} stationId 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStationLog(stationId: string, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<StationLog>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStationLog(stationId, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getStationLog']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStationProfile(stationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlantProfile>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStationProfile(stationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getStationProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listStations(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Station>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listStations(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listStations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} stationId 
         * @param {PlantProfile} plantProfile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setProfile(stationId: string, plantProfile: PlantProfile, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setProfile(stationId, plantProfile, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.setProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} stationId 
         * @param {StationUpdate} stationUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStation(stationId: string, stationUpdate: StationUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateStation(stationId, stationUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} stationId 
         * @param {File} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadAvatar(stationId: string, body: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PlantProfile>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadAvatar(stationId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.uploadAvatar']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async viewAvatar(stationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.viewAvatar(stationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.viewAvatar']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} stationId 
         * @param {Watering} watering 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wateredAtStation(stationId: string, watering: Watering, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wateredAtStation(stationId, watering, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.wateredAtStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {StationInsert} stationInsert 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addStation(stationInsert: StationInsert, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.addStation(stationInsert, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} stationId 
         * @param {Array<StationMeasurement>} [stationMeasurement] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkinStation(stationId: string, stationMeasurement?: Array<StationMeasurement>, options?: RawAxiosRequestConfig): AxiosPromise<Watering> {
            return localVarFp.checkinStation(stationId, stationMeasurement, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStation(stationId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteStation(stationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProfiles(options?: RawAxiosRequestConfig): AxiosPromise<Array<StationPlantProfile>> {
            return localVarFp.getProfiles(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} stationId 
         * @param {string} [period] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStation(stationId: string, period?: string, options?: RawAxiosRequestConfig): AxiosPromise<StationDetails> {
            return localVarFp.getStation(stationId, period, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} stationId 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStationLog(stationId: string, page?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<StationLog>> {
            return localVarFp.getStationLog(stationId, page, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStationProfile(stationId: string, options?: RawAxiosRequestConfig): AxiosPromise<PlantProfile> {
            return localVarFp.getStationProfile(stationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listStations(options?: RawAxiosRequestConfig): AxiosPromise<Array<Station>> {
            return localVarFp.listStations(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} stationId 
         * @param {PlantProfile} plantProfile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setProfile(stationId: string, plantProfile: PlantProfile, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setProfile(stationId, plantProfile, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} stationId 
         * @param {StationUpdate} stationUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStation(stationId: string, stationUpdate: StationUpdate, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateStation(stationId, stationUpdate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} stationId 
         * @param {File} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadAvatar(stationId: string, body: File, options?: RawAxiosRequestConfig): AxiosPromise<Array<PlantProfile>> {
            return localVarFp.uploadAvatar(stationId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        viewAvatar(stationId: string, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.viewAvatar(stationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} stationId 
         * @param {Watering} watering 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wateredAtStation(stationId: string, watering: Watering, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.wateredAtStation(stationId, watering, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {StationInsert} stationInsert 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public addStation(stationInsert: StationInsert, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).addStation(stationInsert, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} stationId 
     * @param {Array<StationMeasurement>} [stationMeasurement] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public checkinStation(stationId: string, stationMeasurement?: Array<StationMeasurement>, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).checkinStation(stationId, stationMeasurement, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} stationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteStation(stationId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteStation(stationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getProfiles(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getProfiles(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} stationId 
     * @param {string} [period] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getStation(stationId: string, period?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getStation(stationId, period, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} stationId 
     * @param {number} [page] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getStationLog(stationId: string, page?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getStationLog(stationId, page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} stationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getStationProfile(stationId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getStationProfile(stationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listStations(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listStations(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} stationId 
     * @param {PlantProfile} plantProfile 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public setProfile(stationId: string, plantProfile: PlantProfile, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).setProfile(stationId, plantProfile, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} stationId 
     * @param {StationUpdate} stationUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateStation(stationId: string, stationUpdate: StationUpdate, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateStation(stationId, stationUpdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} stationId 
     * @param {File} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public uploadAvatar(stationId: string, body: File, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).uploadAvatar(stationId, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} stationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public viewAvatar(stationId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).viewAvatar(stationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} stationId 
     * @param {Watering} watering 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public wateredAtStation(stationId: string, watering: Watering, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).wateredAtStation(stationId, watering, options).then((request) => request(this.axios, this.basePath));
    }
}



