[package]
edition = "2021"
name    = "current-time"
version = "0.1.0"

[dependencies]
bitflags = { version = "2.9.1", features = ["bytemuck"] }
chrono = { version = "0.4.41", default-features = false }