/*
 * Mycelium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StationMeasurement {
    #[serde(rename = "on")]
    pub on: String,
    #[serde(rename = "batteryVoltage")]
    pub battery_voltage: f64,
    #[serde(rename = "temperature")]
    pub temperature: f64,
    #[serde(rename = "humidity")]
    pub humidity: f64,
    #[serde(rename = "lux")]
    pub lux: f64,
    #[serde(rename = "soilPf")]
    pub soil_pf: f64,
    #[serde(rename = "tankPf")]
    pub tank_pf: f64,
}

impl StationMeasurement {
    pub fn new(on: String, battery_voltage: f64, temperature: f64, humidity: f64, lux: f64, soil_pf: f64, tank_pf: f64) -> StationMeasurement {
        StationMeasurement {
            on,
            battery_voltage,
            temperature,
            humidity,
            lux,
            soil_pf,
            tank_pf,
        }
    }
}

