/*
 * Mycelium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StationDetails {
    #[serde(rename = "station")]
    pub station: Box<models::Station>,
    #[serde(rename = "measurements", skip_serializing_if = "Option::is_none")]
    pub measurements: Option<Vec<models::StationMeasurement>>,
}

impl StationDetails {
    pub fn new(station: models::Station) -> StationDetails {
        StationDetails {
            station: Box::new(station),
            measurements: None,
        }
    }
}

