/*
 * Mycelium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StationLog {
    #[serde(rename = "stationId")]
    pub station_id: uuid::Uuid,
    #[serde(rename = "on")]
    pub on: String,
    #[serde(rename = "event")]
    pub event: Box<models::Watered>,
}

impl StationLog {
    pub fn new(station_id: uuid::Uuid, on: String, event: models::Watered) -> StationLog {
        StationLog {
            station_id,
            on,
            event: Box::new(event),
        }
    }
}

