/*
 * Mycelium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StationInsert {
    #[serde(rename = "mac")]
    pub mac: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl StationInsert {
    pub fn new(mac: String, name: String) -> StationInsert {
        StationInsert {
            mac,
            name,
        }
    }
}

