/*
 * Mycelium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Watered {
    #[serde(rename = "period")]
    pub period: String,
    #[serde(rename = "_type")]
    pub _type: String,
}

impl Watered {
    pub fn new(period: String, _type: String) -> Watered {
        Watered {
            period,
            _type,
        }
    }
}

