[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --port /dev/tty.usbserial-54350025201 --log-format defmt"
# runner = "espflash flash --monitor --chip esp32 --port /dev/tty.usbserial-11103 --log-format defmt"

[env]
DEFMT_LOG="info"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
