name: "Dagger CI"
on:
  push:

jobs:
  dagger:
    name: Dagger Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dagger CI
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: >-
            create-client --generator rust --name edge-client-backend \
            export edge-client-backend
      - name: Dagger CI
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: ci