name: "Dagger CI"
on:
  push:

jobs:
  dagger:
    name: Dagger Build and Test
    runs-on: depot-ubuntu-22.04-4,dagger=0.15.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dagger CI
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: create-client rust edge-client-backend --export ./edge-client-backend
      - name: Dagger CI
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: ci