name: "Release backend"
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'backend/deployment/image-tag.yaml'
      
jobs:
  publish:
    name: Dagger publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dagger CI
        uses: dagger/dagger-for-github@8.0.0
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: publish-backend --password env://DOCKERHUB_TOKEN --tag dev-${{ github.sha }}

  update-manifest:
    name: Update ArgoCD Manifest
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update manifest file
        run: |
          cat > backend/deployment/image-tag.yaml << EOF
          imageTag: "dev-${{ github.sha }}"
          EOF
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update backend image tag to dev-${{ github.sha }}"
          title: "Update backend image tag to dev-${{ github.sha }}"
          body: |
            This PR updates the backend image tag to `dev-${{ github.sha }}`.
            
            Once merged, ArgoCD will pick up this change and deploy the new version.
          branch: update-backend-dev-${{ github.sha }}
          delete-branch: true

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dagger CI
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: Build clients
        run: create-client rust edge-client-backend | export edge-client-backend
        shell: dagger {0}
      - name: CI
        run: build-central | export target/release/main
        shell: dagger {0}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev-${{ github.sha }}
          name: Backend Release dev-${{ github.sha }}
          body: |
            Backend release for commit ${{ github.sha }}
            
            Docker image: `dev-${{ github.sha }}`
          files: target/release/main
          token: ${{ secrets.GITHUB_TOKEN }}

