name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      SQLX_OFFLINE: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Branch coverage requires Rust nightly: https://github.com/taiki-e/cargo-llvm-cov/issues/8
      - name: Setup Rust Nightly
        shell: bash
        run: >
          rustup update nightly &&
          rustup default nightly
      - name: Install dependencies
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y dbus-1
      - name: Cargo cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2
        with:
          cache-bin: "false"
      - name: Install Binstall
        uses: cargo-bins/cargo-binstall@ea65a39d2dcca142c53bddd3a097a674e903f475 # main
      - name: Install cargo-llvm-cov
        run: cargo binstall cargo-llvm-cov
      - name: Install Nextest
        run: cargo binstall cargo-nextest
      - name: Run tests with coverage
        run: cargo llvm-cov nextest
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Backend Nextest Results
          files: backend/target/nextest/ci/junit.xml
          disable_search: true
          fail_ci_if_error: true
      - name: Create code coverage report
        run: cargo llvm-cov report --cobertura --output-path ./target/llvm-cov-target/codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Backend Nextest Coverage
          files: backend/target/llvm-cov-target/codecov.json
          disable_search: true
          fail_ci_if_error: true
