name: "Dagger CI"
on:
  push:
  pull_request:

jobs:
  dagger:
    name: Dagger Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Dagger cache
        uses: actions/cache@v4
        with:
          path: .dagger-cache/cargo
          key: dagger-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            dagger-cargo-
      
      - name: Dagger CI (test, lint, build)
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: ci

      - name: Save Dagger cache
        uses: actions/cache@v4
        with:
          path: .dagger-cache/cargo
          key: dagger-cargo-${{ hashFiles('**/Cargo.lock') }}
